### ISSUE TITLE
Any plan to add "mini" icons?

### ISSUE THREAD

**Issue by derick-bai** [nandorojo/react-native-heroicons#2]
I saw that currently you only support outline and solid icons. Any plan to add mini icons?

BTW, great work. And nice TypeScript support 👍🏻

**Comment by nandorojo** [comment]
did these just get added? happy to add support

**Comment by brennanangel** [comment]
@derick-bai From what I understand, the mini icons are 20px x 20px

These are in the project under `react-native-heroicons/blob/master/src/20/solid/`

For example, see `ArrowDownCircle` https://github.com/nandorojo/react-native-heroicons/blob/master/src/20/solid/arrow-down-circle.tsx which has a `viewBox="0 0 20 20"` SVG already.

It might make sense to close this issue
